"""empty message

Revision ID: c7b006b8fd09
Revises: 
Create Date: 2023-08-10 01:46:40.366141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7b006b8fd09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.Column('create_account', sa.String(length=64), nullable=True),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('password',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('reply',
    sa.Column('reply_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.Column('create_account', sa.String(length=64), nullable=True),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('message_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['message.message_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reply_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply')
    op.drop_table('password')
    op.drop_table('user')
    op.drop_table('message')
    # ### end Alembic commands ###
